### PR TITLE
Value to healthz metric, avoid ignoring server when error

### LINKED ISSUE #237: Healthz collector doesn't works
Hi there! 

I found a bug with healtz collector. Url for scrapping incorrectly generated. So I found a solution and a similar PR in this repo: [this](https://github.com/nats-io/prometheus-nats-exporter/pull/232) 

So what the status of fixing this bug? A whole month has passed. 

And I have a suggestion for this metric. I think it's incorrect to show metric like this:
`gnatsd_healthz_status{server_id="http://localhost:8222"} 0` 
when healtz probe is ok. And don't show it at all when server is down.
 `[DBG] ignoring server http://localhost:8222: Get "http://localhost:8222/healthz": dial tcp [::1]:8222: connect: connection refused` (ignoring scraping metrics for disabled server)
My suggestion is to set ok status to 1 and any problem status even server is down to 0 or create more informative metrics for this with showing error. Btw it's relevant after fixing bug with endpoint

Version github.com/nats-io/prometheus-nats-exporter v0.12.0

### PR DESCRIPTION
**Pull request by BinaryArchaism**
Hi there! 

fixes #237

I added value to healthz metric, I think its helpfull, easy to view whats going on. 
It looks like this:

`gnatsd_healthz_status{server_id="http://localhost:8222",value="Get \"http://localhost:8222/healthz\": dial tcp [::1]:8222: connectex: No connection could be made because the target machine actively refused it."} 1`
When error

`gnatsd_healthz_status{server_id="http://localhost:8222",value="ok"} 0`
When ok

I avoid skipping server when its down because its alert situation from my point of view.

### CODE REVIEW

**Comment by kachan28** [comment]
TOP

**Comment by ddbmajor** [comment]
I completely agree, I hope this PR will be merged as soon as possible

**Review by ddbmajor — APPROVED** [review]

**Comment by BinaryArchaism** [comment]
> I think it's best to expose this as a new metric.
> 
> **edit**: @BinaryArchaism sorry it's been a long time. I will rebase and update the PR with a new metric `gnatsd_healthz_status_value` so the others using the existing one won't break.

Hello there! Yes, I think this is a good decision.

File: collector/healthz.go [hunk 1]
```diff
@@ -79,18 +86,36 @@ func (nc *healthzCollector) Describe(ch chan<- *prometheus.Desc) {
...
+		// additional metric to provide more information even if the server connection has issues
+		{
+			var status float64
+			var value string
+			if health.Status == "ok" {
+				status = 1
+				value = health.Status
+			} else {
+				status = 0
+				value = health.Error
```
Comment (mtmk) [inline collector/healthz.go:115]: here we get a long error string. is that acceptable?
```
gnatsd_healthz_status_value{server_id="http://localhost:8222",value="Get \"http://localhost:8222/healthz\": dial tcp [::1]:8222: connectex: No connection could be made because the target machine actively refused it."} 0
```

**Comment by mtmk** [comment]
Example output when server is up:
```
gnatsd_healthz_status{server_id="http://localhost:8222"} 0
gnatsd_healthz_status_value{server_id="http://localhost:8222",value="ok"} 1
```

...when down:
```
gnatsd_healthz_status_value{server_id="http://localhost:8222",value="Get \"http://localhost:8222/healthz\": dial tcp [::1]:8222: connectex: No connection could be made because the target machine actively refused it."} 0
```
(`gnatsd_healthz_status` is not output as before)

File: collector/healthz.go (hunk 1 above)
Comment (wallyqs) [reply collector/healthz.go:115]: I'm not sure this is right, maybe we skip including the error or just make the value `unavailable`?

Comment (mtmk) [reply collector/healthz.go]: fixed. set it to `unreachable` in case of http error otherwise whatever the health status is (which might be `ok`, `error` or `unavailable` coming from the server)

**Review by wallyqs — APPROVED** [review]
