### PR TITLE
Fix missing metrics for server stats not available when exporter is first started

### LINKED ISSUE #242: missing gnatsd_varz_cpu, is nats.io does not have jetstream ready while exporter start
Almost all metrics are missing is 
if nats.io recover jetstream for too long
while nats expoter start.

reproduce
kill nats.io with big jetstream (300GB)
start nats.io
start nats exporter
wait 5>minutes will nats.io recover jetstream and finish start
check metrics most of metrics are missing.

### PR DESCRIPTION
**Pull request by piotrpio**
Fixes #242

This PR, in addition to reevaluating metrics on each `Collect()`, switches exporter from using the `DefaultRegistry` (which is global) to a custom registry stored on `NATSExporter`. This is done to prevent an issue when `Stop()` does not properly unregister collectors modified after being registered (https://github.com/prometheus/client_golang/issues/1430). This issue makes it impossible to restart the exported using `NATSExporter.Stop()` and `NATSExporter.Start()`.

Signed-off-by: Piotr Piotrowski <piotr@synadia.com>

### CODE REVIEW

File: collector/collector.go [hunk 1]
```diff
@@ -395,6 +406,30 @@ func (nc *NATSCollector) objectToMetrics(response map[string]interface{}, namesp
...
+	for k, v := range input {
+		fullKey := k
+		if prefix != "" {
+			fullKey = prefix + "_" + k
+		}
+
+		if nestedMap, ok := v.(map[string]interface{}); ok {
+			nestedKeys := mapKeys(nestedMap, fullKey)
+			for nestedKey := range nestedKeys {
+				keys[nestedKey] = struct{}{}
```
Comment (Jarema) [inline collector/collector.go:423]: we dont't have to have the same prefix logic for nested maps?

**Review by Jarema — COMMENTED** [review]
just one question comment.

File: collector/collector.go (hunk 1 above)
Comment (piotrpio) [reply collector/collector.go:423]: The prefix logic works for keys in nested maps (`nestedKeys`). We don't add the map key itself to the result as it will not be used as a metric. I've added a test for this function which should showcase what's expected:
```go
func TestMapKeys(t *testing.T) {
	m := map[string]any{
		"foo": "bar",
		"baz": "quux",
		"nested": map[string]any{
			"foo": "bar",
			"baz": "quux",
			"nested": map[string]any{
				"foo": "bar",
				"baz": "quux",
			},
		},
	}
	expected := map[string]struct{}{
		"foo":               {},
		"baz":               {},
		"nested_foo":        {},
		"nested_baz":        {},
		"nested_nested_foo": {},
		"nested_nested_baz": {},
	}
	keys := mapKeys(m, "")
	if !maps.Equal(keys, expected) {
		t.Fatalf("expected %v, got %v", expected, keys)
	}
}
```

**Review by Jarema — APPROVED** [review]
LGTM!
